#!/bin/bash
set -eo pipefail

# bitcoin-cli wrapper with automatic rpconnect/chain/datadir/auth configuration

# drop permissions
[ "$EUID" -eq 0 ] && exec s6-setuidgid bitcoin $0 "$@"

host=$(printcontenv BITCOIND_URL | cut -d'/' -f3)
chain=$(printcontenv BITCOIND_CHAIN)
dir=$(printcontenv BITCOIND_DIR || return 0)

# workaround for https://github.com/bitcoin/bitcoin/issues/21295
[ -z "$dir" ] && { dir=/tmp/.bitcoin; mkdir -p $dir; }

printcontenv BITCOIND_AUTH > /dev/null && \
  authargs="-rpcuser=$(printcontenv BITCOIND_AUTH_USER) -rpcpassword=$(printcontenv BITCOIND_AUTH_PASS)"

exec /usr/local/bin/bitcoin-cli -rpcconnect="$host" -datadir="$dir" -chain="$chain" $authargs "$@"
