#!/bin/bash
set -xeo pipefail
shopt -s extglob

apt-get install -yqq --no-install-recommends git \
  $([[ $(dpkg --print-architecture) == "arm"* ]] && echo libatomic1)

useradd -m btcexp
adduser btcexp bitcoin

mkdir /var/log/btc-rpc-explorer && chown nobody /var/log/btc-rpc-explorer

export HOME=/home/btcexp
export PATH=$HOME/node/bin:$PATH

# Install nodejs
wget -qO /tmp/node.tar.gz https://nodejs.org/dist/v$NODEJS_VERSION/node-v$NODEJS_VERSION-$NODEJS_ARCH.tar.gz
echo "$NODEJS_SHA256 /tmp/node.tar.gz" | sha256sum -c -
tar xzf /tmp/node.tar.gz -C $HOME
mv $HOME/node-* $HOME/node && chown -R btcexp $HOME/node

# Install btc-rpc-explorer
wget -qO /tmp/btcexp.tar.gz https://github.com/janoside/btc-rpc-explorer/archive/v$BTCEXP_VERSION.tar.gz
echo "$BTCEXP_SHA256 /tmp/btcexp.tar.gz" | sha256sum -c -

# Trim js code down from 69MB to 3.3MB by bundling the entire tree into a single minified .js file.
# This doesn't work for native libraries, but not having them appears to be acceptable.
# They could be made to work by keeping their dir in node_modules and instructing browserify to skip them with -x.
# They also require build-essential and python3 to be installed during the build.
s6-setuidgid btcexp bash -xeo pipefail << 'PRIV'
  echo The native nodejs modules installation is going to fail. This is normal.
  npm install -g /tmp/btcexp.tar.gz browserify@17.0.0 terser@5.6.0
  if [ -n "$DEV" ]; then mv $HOME/node/lib/node_modules/btc-rpc-explorer $HOME/dist; exit 0; fi

  # hack to fix pug filters
  fix_pug(){ sed 's~function(r){var n=e\[i\]\[1\]\[r\];return o(n||r)}~Object.assign(\0,{resolve:x=>x})~'; }

  mkdir ~/dist ~/dist/bin
  cd $HOME/node/lib/node_modules/btc-rpc-explorer
  (cd bin && browserify --node -r jstransformer-markdown-it -x v8 -x node-bitcoin-script -x async_hooks -x hiredis -x event-loop-stats -x supports-color \
    ./www | fix_pug | terser -c -m reserved=['RpcError'] > ~/dist/bin/www)
  rm -r public/img/screenshots
  mv views public CHANGELOG.md CHANGELOG-API.md ~/dist/
PRIV

# Cleanup
apt-get purge -y git
[ -n "$DEV" ] || rm -rf $HOME/.{npm,cache} $HOME/node/!(bin)
